### ISSUE TITLE
I am looking for a solutionAndroid Voice Processor Documentation Issue

### ISSUE THREAD

**Issue by DevTrinh** [Picovoice/android-voice-processor#6]
Thanks for your awesome android-voice-processor library. I'm looking for a solution to my problem, let's say I have an incoming call, can I change the voice or add effects like inside a restaurant, or a car horn,... or not?

**Comment by laves** [comment]
@DevTrinh - thank you for your interest. The Android Voice Processor is for audio capture only. Audio effects and audio playback are out of the scope of the library. When a call is received, we would recommend stopping AVP's audio capture and starting whatever other audio process you would like.
