### ISSUE TITLE
Bluetooth mic support 

### ISSUE THREAD

**Issue by ghost** [Picovoice/android-voice-processor#7]
I would like to use this library by using a bluetooth headset mic.

I think in `VoiceProcessor.java`, the `AudioRecord` class currently only takes `MediaRecorder.AudioSource.MIC`. By using a bluetooth device, it should also accept `MediaRecorder.AudioSource.VOICE_COMMUNICATION` and enable Bluetooth SCO.

Do you plan to support a bluetooth device mic ?

**Comment by laves** [comment]
@jordan-tpz - thanks for your suggestion. While that does sound like a useful feature, it's not currently on our roadmap as our resources are allocated elsewhere right now. I'll keep this issue open and we'll see if we can add this at some point.

**Comment by laves** [comment]
Apologies, but this didn't make the engineering roadmap and isn't likely to in the near future
